### ISSUE TITLE
Bug: Nested $ calls are not subscribed to

### ISSUE THREAD

**Issue by TGlide** [olehmisar/svelte-reactive#2]
Repro: https://svelte.dev/repl/e22a7779c0824a8fac1f9165139c6954?version=4.1.0

Steps to reproduce:

1. Open repro
2. Click on `Log Second Sum?` checkbox
3. Change values of any of the inputs
4. Observe difference between `Second Sum` and `Second Sum Derived`

**Comment by TGlide** [comment]
I realize this is an odd use case, and one that probably won't be used often. But it'd be important to note this nonetheless

**Comment by olehmisar** [comment]
`derived` specifies `[a, b]` as dependencies and it is re-computed every time either `a` or `b` are changed. In `reactive`, `logSecondSum` is `false` initially, so line `$(a) + $(b)` is never executed and because of that `a` and `b` are never registered as dependencies.

I don't see how I can fix it. If you have any idea how to do it, tell me and I will fix it.

**Comment by TGlide** [comment]
> `derived` specifies `[a, b]` as dependencies and it is re-computed every time either `a` or `b` are changed. In `reactive`, `logSecondSum` is `false` initially, so line `$(a) + $(b)` is never executed and because of that `a` and `b` are never registered as dependencies.
> 
> I don't see how I can fix it. If you have any idea how to do it, tell me and I will fix it.

I also think there is no way to fix it, to be honest 😥Instead, I'd suggest documenting this behaviour in the README. I don't think this will be an issue for most use cases, but it's important to be aware of

**Comment by olehmisar** [comment]
Added a runtime warning and a mention in README. 5904d807fce35d7623a6e4287d5a0ca745ffa1be
